### PR TITLE
Update language file's

### PR DESCRIPTION
**Pull request by AstaRom**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [x] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AstaRom** [comment]
P.S.: Do you think it is necessary to [add a translation](https://github.com/AstaRom/HyperHDR/commit/4584780f3ec57495e08cacb76fe18f3c308afeeb) for the install button?

**Comment by awawa-dev** [comment]
Yes, thanks. The install button also should be translated/

**Comment by AstaRom** [comment]
> Yes, thanks. The install button also should be translated/
Good evening. Updated the commit, added a translation of the new page into other accessible languages ​​and a translation for the button.

**Comment by awawa-dev** [comment]
Thank you. I merged it and your changes are already included in the master branch https://github.com/awawa-dev/HyperHDR/commit/2a338007ed4a0fdcb67f45bad7d11365c3bc975b

**Pull request merged**
