### PR TITLE
Force HyperSerial detection

### PR DESCRIPTION
**Pull request by awawa-dev**
Ignore ProductId/VendorId of the serial port device and force initialization HyperSerial driver. Thanks @alex-013

### CODE REVIEW

**Comment by awawa-dev** [comment]
Hi @AstaRom 
Do you think you would be able to update the translation with the new item: edt_dev_spec_forceSerialDetection? Thank you in advance.

**Comment by AstaRom** [comment]
Good evening, yes I can.
I can do it tomorrow.
Should changes be submitted to the "force_hyperserial" branch?

**Comment by awawa-dev** [comment]
Great 👍 Yes, 'force_hyperserial' branch. It has already been merged with the latest translation resource changes introduced in '20rc1' branch.

**Comment by AstaRom** [comment]
> Do you think you would be able to update the translation

Done.

**Comment by Bascht74** [comment]
Could you add a hint what this feature is for?
Can I set the output path to auto and hyperHDR will look for it?

**Comment by awawa-dev** [comment]
On some systems (mainly due to a udev bug), the system does not report the correct ProductId and VendorId of the Pico board, and HyperHDR could not detect and initialize them correctly. Typically ProductId/VendorId have the value 0, but e.g. in RPi4 they may have the ProductId/VendorId of the USB hub. Correct ProductId/VendorId for Pico is 0xa / 0x2e8a (can be found in the logs).
As it ignores the automatic detection you rather do not want to use it with `auto` ( it may work if there is only one serial device).

**Comment by Bascht74** [comment]
Ok Thx, so if I dont' have any problems with the pi4 I don't need to check it, but it would not hurt?

**Comment by awawa-dev** [comment]
It's better to not use this option if it is not necessary (only when the board is not detected) because it disables important check. This is a workaround for a bug in other software (mainly udev).

**Pull request merged**
