### PR TITLE
Added Wizard Support for more Yeelight products, and workaround for music-mode reset by some of them. (Fixes: #748)

### PR DESCRIPTION
**Pull request by ratawhisk**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by awawa-dev** [comment]
Hi
I took your changes, modified them a bit but I do not have a Yeelight setup to them them.
Could you test it? Branch `testing_750` and also Github Action should finish build installers soon.
If it works, then I could merge both our changes into this PR.

Unfortunately, the Yeelight controller probably suffers from other serious problems because it is very similar to the old Philips Hue controller, which took me a lot of time to sort out and take into account various possible scenarios. Without a test kit, I won't even attempt to refactor this driver in a similar way. So let's hope this small fix will be enough at least for this issue.

**Comment by ratawhisk** [comment]
Hi, I already made a build with my changes, and testet them for about an hour, mostly the music-mode workaround.
But I will test the new version from you for some extendet time tomorrow.

**Comment by awawa-dev** [comment]
Great! Let me know if it works later and merge changes if it is OK. I suspect that the testing time will not be crucial, but rather the turning on and off of the driver , e.g. when the video source has changed. Or physically turning Yeelight lamp off/on to simulate various device state. But I suspect that other things may come out that are not related to this problem, just like in Philips Hue.... Installers: https://github.com/awawa-dev/HyperHDR/actions/runs/7679690184

**Comment by ratawhisk** [comment]
Okay, so i tested different States.

Switching the video source (grabber to color/effect or back) works without problems
restarting HyperHDR didn't cause any problems
Restart the driver from HyperHDR, no problem.

Up to now, the only issue I found, is when I powercycle the bulb.
HyperHDR can't reconnect to the bulb, and disables the device. Reactivating the LED Device component in HyperHDR after some seconds, and it is back to normal.

2024-01-28T14:44:06.669Z [LEDDEVICE4_YEELIGHT] Yeelight device 'yeelink-light-colorc_miapABBB' signals error: 'Write Error: Socket is not connected'
2024-01-28T14:44:06.676Z [LEDDEVICE4_YEELIGHT] (LedDevice.cpp:381) Stopping refresh timer
2024-01-28T14:44:06.676Z [LEDDEVICE4_YEELIGHT] Device 'yeelight' is disabled due to an error: 'All Yeelights in error - stopping device!'
2024-01-28T14:44:06.676Z [COMPONENTCTRL4] LED device: disabled

2024-01-28T14:44:45.392Z [LEDDEVICE4_YEELIGHT] (LedDevice.cpp:247) Enable the device
2024-01-28T14:44:45.392Z [LEDDEVICE4_YEELIGHT] (LedDeviceYeelight.cpp:1203) The music mode server is running at 192.168.1.2:38491
2024-01-28T14:44:45.392Z [LEDDEVICE4_YEELIGHT] (LedDevice.cpp:64) Switch on
2024-01-28T14:44:46.914Z [LEDDEVICE4_YEELIGHT] Yeelight device 'yeelink-light-colorc_miapABBB' signals error: '(-5001) invalid params'
2024-01-28T14:44:47.414Z [LEDDEVICE4_YEELIGHT] Ignoring Yeelight error when turning off music mode
2024-01-28T14:44:48.079Z [LEDDEVICE4_YEELIGHT] (LedDevice.cpp:367) Starting timer with interval = 10ms
2024-01-28T14:44:48.079Z [COMPONENTCTRL4] LED device: enabled

**Comment by awawa-dev** [comment]
Thank you for your tests and feedback. I added an autoresume for Yeelight: can you check it? https://github.com/awawa-dev/HyperHDR/actions/runs/7687019660

**Comment by ratawhisk** [comment]
Tested it a few times, and yes, works perfectly! Always at the first Switch on try, the LED gets back in action.



2024-01-28T18:29:23.380Z [LEDDEVICE4_YEELIGHT] Yeelight device 'yeelink-light-colorc_miapABBB' signals error: 'Write Error: Socket is not connected'
2024-01-28T18:29:23.394Z [LEDDEVICE4_YEELIGHT] Device 'yeelight' is disabled due to an error: 'All Yeelights in error - stopping device!'
2024-01-28T18:29:23.394Z [COMPONENTCTRL4] LED device: disabled
2024-01-28T18:29:26.546Z [LEDDEVICE4_YEELIGHT] The LED device is not ready... trying to reconnect (try 1/60).
2024-01-28T18:29:26.546Z [LEDDEVICE4_YEELIGHT] (LedDeviceYeelight.cpp:1206) The music mode server is running at 192.168.1.2:40219
2024-01-28T18:29:26.685Z [LEDDEVICE4_YEELIGHT] (LedDevice.cpp:64) Switch on
2024-01-28T18:29:27.718Z [LEDDEVICE4_YEELIGHT] Yeelight device 'yeelink-light-colorc_miapABBB' signals error: '(-5001) invalid params'
2024-01-28T18:29:28.218Z [LEDDEVICE4_YEELIGHT] Ignoring Yeelight error when turning off music mode
2024-01-28T18:29:28.859Z [LEDDEVICE4_YEELIGHT] (LedDevice.cpp:392) Stopping retry timer
2024-01-28T18:29:28.860Z [COMPONENTCTRL4] LED device: enabled

**Comment by awawa-dev** [comment]
Thank you again. I combined our changes in this PR. Check if it's OK and test the latest build. If you don't find any new problems then I will merge your PR within a few days.

**Comment by ratawhisk** [comment]
Okay, i will do that.

**Comment by ratawhisk** [comment]
Up to today, everything worked fine.

No new problems!

**Comment by awawa-dev** [comment]
OK, thank you for the feedback. I just merged these changes.

**Comment by DrConflict** [comment]
Just to confirm, it's normal to get this " Ignoring Yeelight error when turning off music mode" log in v20.0 right? There's no way to permanently disable the music mode?

**Comment by awawa-dev** [comment]
You **really** do not want the music mode which is using UDP even if it is possible (I dont know if it is). For Philips Hue there is a huge difference when similar entertainment mode (UDP) is enabled or not (REST on TCP). But Philips Hue is a different league in terms of API quality.

**Pull request merged**
