### PR TITLE
add systemwrapper check to api toggle for hdr global

### PR DESCRIPTION
**Pull request by mariokakoulli**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by awawa-dev** [comment]
Hi
Thank you for the PR. I think it should work. But as a side effect, when using the tone mapping switch, it unnecessarily consumes an additional ~50MB of RAM (new LUT for DX grabber even when not used) for users who do not want to use the DX system grabber because they only use the USB grabber and we need to think about how to solve it.

**Comment by mariokakoulli** [comment]
some kind of identifier in each grabber with a status of if it's being used or not then an if check where i added the new commit?

**Comment by awawa-dev** [comment]
Please check out the new feature which should automatically detect your system's HDR mode when HyperHDR DirectX 11 grabber is used, so you probably won't need to manually control tone mapping anymore #691

**Comment by mariokakoulli** [comment]
i haven't had the time to test it extensively but from some usage the past couple of days it looks good to me, the performance improvement in particular, thanks for the hard work! i'll close this as the branch is no longer needed

**Comment by awawa-dev** [comment]
OK, if further tests show that such a toggle would be needed, feel free to open it again. I think we will be able to come up with something so that this switch does not conflict with other configurations.

**Pull request closed without merging**
