### PR TITLE
Allow LUT calibration when no USB grabber is present

### PR DESCRIPTION
**Pull request by awawa-dev**
Allows to use other than USB video source for the HDR to SDR tone mapping LUT calibration, when the grabber is not present or the video grabber support was disabled in the build configuration.

### CODE REVIEW

**Comment by satgit62** [comment]
Hi, since there is no documentation here for the LUT calibration for LG webOS, wanted to know if the calibration for webOS still requires using a Windows computer capable of displaying HDR content and having HyperHDR installed. The Windows computer must be connected to the HDMI input of the TV so that the calibration page is displayed on the TV screen (as HDR content) and live preview in HyperHDR (captured by the grabber). Does HyperHDR then have to get data from webOS Grabber via flatbuffer, or the calculation simply follows via the instance screen capture with priority 245 and the tone mapping from HDR to SDR in software screen capture should be switched off? 
What is the best way to proceed here?
Thanks in advance.

**Comment by asturel** [comment]
I'm also unable to get calibration to start with flatbuffer, seems like the ``LutCalibrator::assignHandler`` method:<https://github.com/awawa-dev/HyperHDR/blob/5950b22b25c3aa1f018b020543c80076e667e252/sources/utils/LutCalibrator.cpp#L106> never called when flatbuffer is the source (I tried adding extra logging by <https://github.com/asturel/HyperHDR/commit/caa2bc88933b4c5e9a5f8efa9248d50e49d4c21b>). The JsonAPi ``lut-calibration`` method returns 
```json 
{"success": true, "command": "lut-calibration", "tan": 1} 
```
<https://github.com/awawa-dev/HyperHDR/blob/5950b22b25c3aa1f018b020543c80076e667e252/sources/api/JsonAPI.cpp#L1346>

But there's nothing in the logs with "CALIBRATOR".

**Comment by awawa-dev** [comment]
Hi
It's very outdated sources but it's invoked by https://github.com/awawa-dev/HyperHDR/blob/5950b22b25c3aa1f018b020543c80076e667e252/sources/api/JsonAPI.cpp#L1342 via signal.
I just want to explain that the changes in the beta were available for 3 months and you could then submit comments that were taken into account on an ongoing basis. Currently, I'm taking a long well-deserved break from coding after the release of v20. The configuration without a grabber is not included in my tests because I treat it as a niche setup and I dont have grabberless setup like WebOS (BTW which limit performance of calibration by performing YUV to RGB conversion on its own). But of course, if you find a problem and are able to propose a solution, open a PR. If I have an idea, I will try to advise you.

**Comment by asturel** [comment]
Thanks, yeah sorry for that, I found that call, but "for some" reason the connected signal actually never runs in the lut calibrator, my guess was the same: its because we have no grabber, I've checked the ifdefs, some events but couldn't figure out, i hoped you have some idea how should/could debug this. Thanks for v20, enjoy your deserved relaxing.

**Comment by awawa-dev** [comment]
Thanks. The model (both calibrator and grabber handler) was rewritten before beta1 and it has changed completely. But now that I looked into current code the issue may be here: 
https://github.com/awawa-dev/HyperHDR/blob/52f12b4ec9753f0b00ddeeb98d709b15b55a0444/sources/api/HyperAPI.cpp#L1031
it should be check for nullptr:
```_lutCalibrator->incomingCommand(_instanceManager->getRootPath(), (_videoGrabber != nullptr) ? _videoGrabber->grabberWrapper() : nullptr, getActiveComponent(), checksum, _startColor, _endColor, limitedRange, saturation, luminance, gammaR, gammaG, gammaB, coef);```

**Comment by asturel** [comment]
Thanks, turned out the issue was "related to grabbers", I haven't checked that the issue is persist on the latest codebase, but it  was the following:
Every grabber ctor registered the ColorRgb metatype: 
```cpp
qRegisterMetaType<Image<ColorRgb>>("Image<ColorRgb>");
````
, but since we had no grabber, we run into this error:

```
QObject::connect: Cannot queue arguments of type 'ColorRgb'
(Make sure 'ColorRgb' is registered using qRegisterMetaType().)
```

**Comment by awawa-dev** [comment]
Strange... the type is registered when the main daemon starts https://github.com/awawa-dev/HyperHDR/blob/52f12b4ec9753f0b00ddeeb98d709b15b55a0444/sources/hyperhdr/HyperHdrDaemon.cpp#L89

**Comment by awawa-dev** [comment]
Probably ColorRgb could be also registered there.

**Comment by asturel** [comment]
I dont know why, but ``qRegisterMetaType<Image<ColorRgb>>("Image<ColorRgb>"); `` didnt worked for me, only ``	qRegisterMetaType<ColorRgb>("ColorRgb");`` (i did it in LutCalibrator ctor)

**Comment by awawa-dev** [comment]
If the Image<ColorRgb> type was not registered, you would not have a preview in the live preview window because it is also sent there by signals. I suspect that in the older version this could have resulted from a different life cycle of the calibrator (the moment in which it was created), but this was later changed. You will definitely need a fix https://github.com/awawa-dev/HyperHDR/pull/518#issuecomment-2025721396 in the latest version and it should work.
BTW you probably also need to disable tone mapping in flatbuffer before you start calibration. Otherwise strange things may happen.

**Pull request merged**
