### PR TITLE
Add support for HD108 led strip (16bits colors)

### PR DESCRIPTION
**Pull request by awawa-dev**
Add initial support for HD108 SPI led strip.
HD108 is capable of 16bits channels for RGB and adjust the maximum current output level.
The LED strip is using standard 5V logic level (not 3.3V).

obraz

Documentation can be found here: [http://www.rose-lighting.com/wp-content/uploads/sites/53/2021/03/HD108-5050-LED-Specificaion-V1.1.0-Rose-Lighting.pdf](https://www.rose-lighting.com/wp-content/uploads/sites/53/2021/03/HD108-5050-LED-Specificaion-V1.1.0-Rose-Lighting.pdf)

### CODE REVIEW

**Comment by r3vEngIT** [comment]
took longer than expected but i got this running. 
this is all new to me and i am determined to learn haha.
i was using the SD card .img, so i had to teach myself how to SSH into the RPi to use this .deb file. but something with the file format linked here would not work with 'wget' so i had to learn how to use SCP and load it that way. 

i also did more reading on these led chips and found an updated datasheet from ROSE. 
[HD108-Specificaion-V1.2.pdf](https://github.com/awawa-dev/HyperHDR/files/10977563/HD108-Specificaion-V1.2.pdf)
**they verify the chip's ability to use 3.3V logic**

i re-designed my LED frame and further improved my wiring. the RPi is now powered directly from the PSU instead of off the strip. the cable from the RPi to the strip has been shortened to ~8in.  originally it was ~20in. 

the BAD: 
the colors are off but i cant figure out exactly why. i have been reading about color management and started playing around with different ICC profiles within windows because i think that is where the problem lies.
being an audiophile and chasing that bitstream quality i have learned of the ways in which signal processing can have a significant impact on quality.  between nvidia, windows, my Onkyo, sony TV, screen capturing, HDR and EDID handshakes it is a never-ending battle using a HTPC.

so i think the HD108s are only amplifying the color issues. using youtube color tests, the LED colors are perfect for the basic colors. but when watching a movie (SDR or HDR) the tones are too light and the overall brightness of the LEDs is too high. adjusting gamma over 2.0 helps this but introduces other issues like skin pigment being reddish. 

i am going to keep messing with it but if there is any data you would like to see, i can send it to you. 

is there any network protocols that will screen capture at higher than 8bit?

can you take a look at the new datasheet and see if there is anything different that would need changed in HyperHDR?

Thanks again!

**Comment by awawa-dev** [comment]
> i also did more reading on these led chips and found an updated datasheet from ROSE. (adds 3.3V logic proof)

It is probably a rather different version of HD108, the previous manual has the same authors and the other revision was not compatible with 3.3V. The situation is the same with some versions of ws2812b in the market. The HD108 protocol hasn't changed.

>i think the HD108s are only amplifying the color issues. using youtube color tests, the LED colors are perfect for the basic colors. but when watching a movie (SDR or HDR) the tones are too light and the overall brightness of the LEDs is too high. adjusting gamma over 2.0 helps this but introduces other issues like skin pigment being reddish.

Yes, you only need to watch the live video preview and not the LEDs as some minor transformations like gamma correction have been applied to them by default. The symptom you describe is usually when "HDR to SDR tone mapping" is unnecessarily enabled in the DX11 grabber, which may cause the overall brightness to be too high. If you search the discussion, you'll find a similar issue with DX capture, where some content doesn't require HDR tone mapping (like desktop apps) and other apps need it (e.g. games). There is no workaround for now.

**Comment by r3vEngIT** [comment]
> > i also did more reading on these led chips and found an updated datasheet from ROSE. (adds 3.3V logic proof)
> 
> It is probably a rather different version of HD108, the previous manual has the same authors and the other revision was not compatible with 3.3V. The situation is the same with some versions of ws2812b in the market. The HD108 protocol hasn't changed.
> 
> > i think the HD108s are only amplifying the color issues. using youtube color tests, the LED colors are perfect for the basic colors. but when watching a movie (SDR or HDR) the tones are too light and the overall brightness of the LEDs is too high. adjusting gamma over 2.0 helps this but introduces other issues like skin pigment being reddish.
> 
> Yes, you only need to watch the live video preview and not the LEDs as some minor transformations like gamma correction have been applied to them by default. The symptom you describe is usually when "HDR to SDR tone mapping" is unnecessarily enabled in the DX11 software grabber, which may cause the overall brightness to be too high. If you search the discussion, you'll find a similar issue with DX capturing, where some content doesn't require HDR tone mapping (like desktop apps) and other apps need it (e.g. games). There is no workaround for now.

oh wow. 
glad you mentioned this or i probably never would have looked!

Screenshot 2023-03-18 200207

looks like @ktaeleman is working on improving HSC for R16G16B16 Windows Desktop Duplication. i will focus my research here. 

https://github.com/sabaatworld/HyperionScreenCap/pull/61#issue-1531537915

**Comment by r3vEngIT** [comment]
update:
running the modified HSC with the HD108 is working well so far. colors are the best i have seen and auto HDR turned on in Windows 11 is working (surprisingly) as well.

Thanks again for all your help!

**Pull request merged**
