### PR TITLE
Update language file's

### PR DESCRIPTION
**Pull request by AstaRom**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

- Update language file's

### CODE REVIEW

**Comment by awawa-dev** [comment]
Thank you. I will include it before final v20 release.

**Comment by AstaRom** [comment]
- Updated to latest changes 'v20rc' ( https://github.com/awawa-dev/HyperHDR/pull/705/commits/f2ad6b6e92e00c0c10458fd09717b1a9394c00e4 )
- Update development time

**Comment by AstaRom** [comment]
- Just cleaning up the code from extra spaces and tabstops

**Comment by awawa-dev** [comment]
Hi
The changes tend to grow a bit and may be difficult to track especially before main HyperHDR release, perhaps not because of their complexity but because of the number of modified files. Maybe we can do it so that you add your changes limited to the i18 translation files along with the changed HyperHDR license in the main directory in the commit to the v20rc branch, which is a v20 release candidate and contains corrections to the bugs found in the beta? Another issue is those unfortunate Microsoft editors... they will always enter empty characters, I've tried everything and they just have it that way and I don't think it's worth correcting it any further: it just has to be that way.

**Comment by AstaRom** [comment]
> commit to the v20rc branch

Moved changes to branch.

> Another issue is those unfortunate Microsoft editors...

I'm using Notepad++
When I edit something, then after completion I replace spaces and tabs using the 'search and replace' command.

Screenshot_1

I also activate the option to replace tabs with spaces.

Screenshot_2

**Comment by awawa-dev** [comment]
Notepad++ is good editor but not suitable as IDE and the problem exists in Visual Studio Community Edition and Code.

**Pull request closed without merging**
