### PR TITLE
Added support for entertainment api v2 (hue gradient strips)

### PR DESCRIPTION
**Pull request by gibahjoe**
**Summary**
This PR adds support for Philips hue entertainment API version 2. Version 1 of the API does not support the gradient light strip showing multiple colors of light. In the entertainment API v2, the concept of channels was introduced. This means that a hue light could have multiple channels (e.g the gradient light strip)and a channel could have multiple lights and it's these channels that are addressed when coloring the lights. This feature can be enabled as described in the attached image.

sshot

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:
**Before**
IMG_6875

** After **
IMG_6874

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [x] This PR was brought about following this discussion here. https://github.com/awawa-dev/HyperHDR/discussions/469

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**
- Because a hue light can have multiple channels, the `Power off on black` has been removed when using API v2
- Because a hue light can have multiple channels as well as a channel having multiple lights, the color space calculation has been removed. Also, its also documented by hue that if a color out of the color space of a light is selected, it resolves it to the closest color within its color space
- Philips hue documentation https://developers.meethue.com/develop/hue-api-v2/migration-guide-to-the-new-hue-api/

**Disclaimer**
This is the first time I have programmed in c++ since the days of BlackBerry 10 OS. So if there are any issues, let me know.

### CODE REVIEW

**Comment by dbell669** [comment]
Initial Tests show the V2 API working successfully, with some changes from the V1 API. When running the entertainment set up, lights no longer appear to be added to the list indiividually, appearing as quadrants. 
image.

**Comment by dbell669** [comment]
As another note, it seems that the light ids no longer appear to match up to a single light. This may be because I have multiple gradient lights, but they seem to affect different zones instead of the individual lights. This makes placing light locations much more difficult.

**Comment by awawa-dev** [comment]
You can blink the particular LED to identify it using this:
obraz

**Comment by dbell669** [comment]
That's what I've been using to try to place them the best I can. The issue I'm having is that a single light id is affecting multiple separate lights. I'd 0 will blink my play strip, my gradient floor lamp, and table lamp.

**Comment by awawa-dev** [comment]
I think for API v2 when settings the color for the lamp in the wizard, new format command should be used: httpX://<ipaddress>/clip/v2/resource/light/<v2-id> instead of API v1 httpX://<ipaddress>/api/<appkey>/lights/<v1-id>/state (it generates all behavior where the gradient strip is one lamp). And the passed json has also different format. @gibahjoe could you take a look?

**Comment by gibahjoe** [comment]
> That's what I've been using to try to place them the best I can. The issue I'm having is that a single light id is affecting multiple separate lights. I'd 0 will blink my play strip, my gradient floor lamp, and table lamp. As a result I can't separate each light segment into its own channel .

The only way that will happen is if you have multiple lights on the same channel.

Would you mind making an api call and sharing the response here? I can prepare it and send to you if you are interested.

**Comment by dbell669** [comment]
Sure, happy to help. May take me a day or two to run it but I'm more than happy to.

**Comment by gibahjoe** [comment]
- Please make the below api calls on your terminal and share the response. 
- what is the name of the entertainment area you are trying to configure?
- You can get the ip address and the username from the configuration page for the Philips Hue

```
curl --location --request GET 'https://{{HUE_IP_ADDRESS}}/clip/v2/resource/entertainment_configuration' \
--header 'hue-application-key: {{HUE_USERNAME}}'
```

```
curl --location --request GET 'https://{{HUE_IP_ADDRESS}}/clip/v2/resource/entertainment' \
--header 'hue-application-key: {{HUE_USERNAME}}'
```

**Comment by gibahjoe** [comment]
> ~I think for API v2 when settings the color for the lamp in the wizard, new format command should be used: httpX://ipaddress/clip/v2/resource/light/[v2-id] instead of API v1 httpX://ipaddress/api/[appkey]/lights/[v1-id]/state (it generates old behavior where the gradient strip is one lamp). And the passed json has also different format.~
> `void LedDevicePhilipsHueV2::identify(const QJsonObject &params)` in PR is rewritten so I also think it is a Philips Hue user configuration issue. @gibahjoe could you take a look?

I am on it

**Comment by dbell669** [comment]
Running the commands with https gives me

root@LGwebOSTV:~# curl --location --request GET 'https:/(IP_Address)/clip/v2/resource/entertainment_configuration' \--header 'hue-application-key: (HUE_KEY)'
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

removing https and placing http gets me 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <title>hue personal wireless lighting</title>
    <link rel="stylesheet" type="text/css" href="/index.css">
</head>
<body>
    <div class="philips-header">
      Philips
    </div>
    <div class="header">
      hue personal wireless lighting

      

    </div>
    <div class="error">Oops, there appears to be no lighting here</div>
</body>
</html>


Did I do something wrong on the install?

**Comment by gibahjoe** [comment]
HI, I added the ```insecure``` flag to ignore ssl. see updated commands below

```bash
curl --insecure --location --request GET 'https://{{HUE_IP_ADDRESS}}/clip/v2/resource/entertainment_configuration' \
--header 'hue-application-key: {{HUE_USERNAME}}'
```

```bash
curl --location --request GET 'https://{{HUE_IP_ADDRESS}}/clip/v2/resource/entertainment' \
--header 'hue-application-key: {{HUE_USERNAME}}'
```

**Comment by dbell669** [comment]
> @dbell669
> 
> * Please make the below api calls on your terminal and share the response.
> * what is the name of the entertainment area you are trying to configure?
> * You can get the ip address and the username from the configuration page for the Philips Hue
> 
> ```shell
> curl --location --request GET 'https://{{HUE_IP_ADDRESS}}/clip/v2/resource/entertainment_configuration' \
> --header 'hue-application-key: {{HUE_USERNAME}}'
> ```
> 
> ```shell
> curl --location --request GET 'https://{{HUE_IP_ADDRESS}}/clip/v2/resource/entertainment' \
> --header 'hue-application-key: {{HUE_USERNAME}}'
> ```

Enertainment zone is called Game Zone. I am aslo getting the same messages with the --insecure tag.

**Comment by dbell669** [comment]
Was able to get the files. Turns out I just needed to change the port to 443 in the curl command. Entertainment zone is called Game_Zone.
[hue_output_Entertainment_Configuration.txt](https://github.com/awawa-dev/HyperHDR/files/10419673/hue_output_Entertainment_Configuration.txt)
[hue_output_Entertainment.txt](https://github.com/awawa-dev/HyperHDR/files/10419674/hue_output_Entertainment.txt)

**Comment by gibahjoe** [comment]
You have multiple lights in a channel. I suspect this is due to how you positioned your lights in the entertainment configuration so there is some overlap.

This means that when you click that identification button, whichever device that lights  up have channels that will show the same color.

If you could send a screenshot of your game zone light placements from the hue app, that will help me confirm or disprove my hypothesis.

If I am correct about the above,
A workaround if you need full control (you don't want channels to be grouped) will be to create an entertainment area and place the lights in completely different locations where they won't overlap.

In the meantime, I will update this PR to identify channels instead of lights for v2 (only the channels will light up instead of the entire light).

**Comment by dbell669** [comment]
Screenshot_20230116-102358_Hue


Does that work?

**Comment by dbell669** [comment]
It seems I have too many lights for the placement workaround to work. Is there a way to seperate the channels back to lights in the v2 api?.

**Comment by gibahjoe** [comment]
Did you try placing them very far apart even towards the couch in the image above? 

Please note that this issue you are experiencing is just for initial placement. Just complete the wizard, everything should work as usual. If the placements are off, you can correct this in the  "led layout" tab in HyperHDR.

Please try that and let us know the outcome. 

I will update this PR so that it's just the channels (segments) of gradient strips/lamps that flash not the entire light/lamp. This should cause less confusion than flashing the entire device

**Comment by gibahjoe** [comment]
If you complete the wizard and start syncing, what behavior do you experience?

**Comment by dbell669** [comment]
Same as before unfortunately. Multiple lights light up when testing channels

**Comment by gibahjoe** [comment]
@awawa-dev I just pushed up an update to the identify for v2 api. This update flashes the channels (segments) of a gradient strip for instance instead of the entire light. This should help with Identification. Please review

@dbell669 Please update to the latest push and let us know what you experience.

**Comment by awawa-dev** [comment]
Hi @gibahjoe 
Thanks for the update. I not a fan of initializing Philips Hue in the identify method but I understand it's necessary to make the  stream writes works: so if it solves the last problem and @dbell669 confirms it, I'm OK with that. I was thinking also about extending the late configuration phase and add blink to the context menu which was introduced here: https://github.com/awawa-dev/HyperHDR/pull/379 . The device should be already initialized then. In fact the 'blink' can be used even now by disabling a led in the context menu for a moment to identify it.

**Comment by gibahjoe** [comment]
@awawa-dev 

I will take a Look at that over the weekend.

**Comment by awawa-dev** [comment]
Ok, no problem. There are two minor issues/warning when compiling on webOS:
- I will convert spaces to tabs before merging anyway
obraz
-
obraz

**Comment by gibahjoe** [comment]
> Ok, no problem. There are two minor issues/warning when compiling on webOS:
> 
> * I will convert spaces to tabs before merging anyway
>   obraz
> 
> obraz

I will clean this up too

**Comment by gibahjoe** [comment]
> So after applying the new version, I wasn't able to see much difference in the the led setup. The lights were still on multiple channels and could not be individually places. I noticed that actually testing the lights became more difficult as hitting the identify button would not blink the lights until I left the hue entertainment wizard

The channels alternate between red, blue, green. It might be difficult to notice if you have an active stream going on. Could you try agin and share your logs. Sorry for bothering you.

**Comment by dbell669** [comment]
No problem at all. I'm happy to help if I can find a way to remove the sync box and put it somewhere else. I can get you the logs shortly. I do see them alternate between the three colors. I'm more worried about the lag at this point, but I can try without an active stream and see what I can get to you.

**Comment by dbell669** [comment]
[hue_identify_log.txt](https://github.com/awawa-dev/HyperHDR/files/10469013/hue_identify_log.txt)

Heres my log. let me know if you need anything else

**Comment by dbell669** [comment]
I've also noticed that it now has random signal drops on occasion, but I dont know if its the blackbar detection or something else

**Comment by dbell669** [comment]
The update seems to have made no change in the selection of lights. The channels are still hitting multiple lights. I guess the next thing i was going to look at was how my placement was working. should I be trying to place these in the context of an LED frame or by letting the config wizard handle it?

**Comment by awawa-dev** [comment]
- @dbell669 as you can see a warning you have enabled grouping in the LED strip configuration. So light no. 1 and no. 2 are sharing the same color and is affecting the testing for sure. You can correct it in applying the same group setting attribute as it's shown on the following screenshot. The question is how this setting was activated? Did you edited the LED strip configuration manually? Make sure the warning about grouping disappears after your changes.
obraz

- @dbell669 could you check your build version 'advanced->about->system report->build Now when you click the 'identify button' you should see a sequence of: red, green, blue colors in the interval of 1 second. Do you confirm such behavior?

- @gibahjoe if there is a collection in devicesId could it send the command to the whole group despite you have rewritten the identify method to use the stream?
obraz

**Comment by awawa-dev** [comment]
The compiler warnings are fixed now, restored formatting in ProviderRestApi.cpp and added a check for a group to be not included when Entertainment API is disabled.

**Comment by dbell669** [comment]
OK. I fixed the grouping, now it looks like 
image
[group config.txt](https://github.com/awawa-dev/HyperHDR/files/10474964/group.config.txt)

There is an issue when hitting the identify buttons on the lights. they seem to crash the hyperhdr UI and make navigation unusable. it seems to come back after a few secons, and most of the time it will identify itself with the R/B/G sequence after it recovers. This makes the hue wizard basically unusable on my end. The initial method of having them blink blue worked. I believe my initial issue with identification stemmed from the lights sharing channels.  Is there a way to seperate the channels back into their own lights, or is this a consequence of the move to the v2 api?

System Version
master (awawa-dev-3502af9/6ebbb93-1674302206)

**Comment by awawa-dev** [comment]
Thanks for the feedback: probably the main thread is taking too much time to send 'identify' messages to lamps (because now we initialize Philips Hue fully then) so the websocket from UI thinks that it's down because it is not responding in time or HyperHDR is crashing and the service is bringing it back (but I'm not sure if it works that way on webos, rather e.g. for systemd on Rpi).

Did you have Philips Hue instance working (sending colors stream) before you ran the wizard now? If so try to disable it first in the remote tab and then run the wizard when everything stops to work.

**Comment by dbell669** [comment]
I had philips hue working  and sending colors before the push that started to use the red blue green flashing. even with it disabled in the remote tab its still not handling the flash action well. it wont seem to send them until after I close the wizard. So I can set locations, but trying to ping them does not work.

**Comment by gibahjoe** [comment]
Hi, sorry I had a busy weekend. @dbell669 using channels is a consequence of api v2 but what I don't know is why the philips hue system has added multiple lights to one channel. I have tried escalating to their team but I am not getting any feedback. Is it possible you grouped the lights somehow (either using third party apps etc)? My setup has 1 gradient strip and a few bulbs so it's just guesswork at this point. As for the lag issue with identify, I will further optimize that. Expect an update soon.

**Comment by gibahjoe** [comment]
@awawa-dev 

Taking a look at the last log sent by @dbell669  (relevant parts below), the initialization does not seem to be the problem 

```
2023-01-20T18:14:47.441Z [WEBSOCKET] (JsonAPI.cpp:1630) message: [{"command":"leddevice","ledDeviceType":"philipshuev2","params":{"channelId":9,"clientkey":"166714F14535C644BF55E371CE4965E4","entertainmentConfigurationId":"14b3d2fa-d52f-4025-bf05-fc54000eda39","host":"192.168.1.3:443","user":"hK-3rTHmCqTKkr5B3n1VTWSdVC7W4ewrr5ZgIlQf"},"subcommand":"identify","tan":1}]
2023-01-20T18:14:47.441Z [LEDDEVICE_PHILIPSHUEV2] (LedDevicePhilipsHueV2.cpp:1355) params: [{"channelId":9,"clientkey":"166714F14535C644BF55E371CE4965E4","entertainmentConfigurationId":"14b3d2fa-d52f-4025-bf05-fc54000eda39","host":"192.168.1.3:443","user":"hK-3rTHmCqTKkr5B3n1VTWSdVC7W4ewrr5ZgIlQf"}]
2023-01-20T18:14:47.442Z [LEDDEVICE] (ProviderRestApi.cpp:170) GET begin: [https://192.168.1.3:443/auth/v1] []
2023-01-20T18:14:47.447Z [LEDDEVICE] (ProviderRestApi.cpp:191) GET end (5 ms): [https://192.168.1.3:443/auth/v1] []
2023-01-20T18:14:47.448Z [LEDDEVICE] (ProviderRestApi.cpp:310) Reply.httpStatusCode [200]
2023-01-20T18:14:47.448Z [LEDDEVICE_PHILIPSHUEV2] (LedDevicePhilipsHueV2.cpp:515) Application ID is 3a91a748-d600-4a22-b471-f884d0d1fb01
2023-01-20T18:14:47.448Z [LEDDEVICE_PHILIPSHUEV2] (LedDevice.cpp:168) deviceConfig: [{"host":"192.168.1.3","hs_attempts":5,"hs_timeout_max":2000,"hs_timeout_min":600,"psk":"166714F14535C644BF55E371CE4965E4","psk_identity":"hK-3rTHmCqTKkr5B3n1VTWSdVC7W4ewrr5ZgIlQf","refreshTime":20,"retry_left":60,"seed_custom":"dtls_client","servername":"Hue","sslport":2100,"type":"philipshuev2"}]
2023-01-20T18:14:47.448Z [LEDDEVICE_PHILIPSHUEV2] (LedDevice.cpp:222) Refresh interval = 20ms
2023-01-20T18:14:47.448Z [LEDDEVICE_PHILIPSHUEV2] (LedDevice.cpp:197) Device is not ready to start a timer
2023-01-20T18:14:47.448Z [LEDDEVICE_PHILIPSHUEV2] (LedDevice.cpp:232) RefreshTime updated to 20ms
2023-01-20T18:14:47.448Z [LEDDEVICE_PHILIPSHUEV2] (ProviderUdpSSL.cpp:122) Successfully parsed 192.168.1.3 as an ip address.
2023-01-20T18:14:47.448Z [LEDDEVICE_PHILIPSHUEV2] (ProviderUdpSSL.cpp:153) UDP SSL using 192.168.1.3:2100
2023-01-20T18:14:47.448Z [LEDDEVICE_PHILIPSHUEV2] Channel ID 9 ("", LED index "9") created
2023-01-20T18:14:47.448Z [LEDDEVICE] (ProviderRestApi.cpp:170) GET begin: [https://192.168.1.3:443/clip/v2/resource/entertainment_configuration/14b3d2fa-d52f-4025-bf05-fc54000eda39] []
2023-01-20T18:14:47.481Z [LEDDEVICE] (ProviderRestApi.cpp:191) GET end (33 ms): [https://192.168.1.3:443/clip/v2/resource/entertainment_configuration/14b3d2fa-d52f-4025-bf05-fc54000eda39] []
2023-01-20T18:14:47.482Z [LEDDEVICE] (ProviderRestApi.cpp:310) Reply.httpStatusCode [200]
2023-01-20T18:14:47.484Z [LEDDEVICE_PHILIPSHUEV2] (LedDevicePhilipsHueV2.cpp:352) Group state                   : {"channels":[{"channel_id":0,"members":[{"index":0,"service":{"rid":"d0563cd5-1225-48b9-abbf-92d053fc55d9","rtype":"entertainment"}},{"index":0,"service":{"rid":"92fd41bb-9c1c-487e-8d90-4510b9b24c48","rtype":"entertainment"}},{"index":2,"service":{"rid":"5501ca92-e622-4ec3-867b-27546a8e61cf","rtype":"entertainment"}},{"index":6,"service":{"rid":"d6fe9cdb-9c12-4f17-9ef2-401fbf548f2f","rtype":"entertainment"}}],"position":{"x":0.4,"y":0.8,"z":-0.4}},{"channel_id":1,"members":[{"index":1,"service":{"rid":"d0563cd5-1225-48b9-abbf-92d053fc55d9","rtype":"entertainment"}},{"index":1,"service":{"rid":"92fd41bb-9c1c-487e-8d90-4510b9b24c48","rtype":"entertainment"}},{"index":5,"service":{"rid":"d6fe9cdb-9c12-4f17-9ef2-401fbf548f2f","rtype":"entertainment"}}],"position":{"x":0.4,"y":0.8,"z":0}},{"channel_id":2,"members":[{"index":0,"service":{"rid":"385e5a28-cc18-4283-90d9-27f755e49d18","rtype":"entertainment"}},{"index":0,"service":{"rid":"722b1dec-d270-41f3-8a74-ff56e3bc104d","rtype":"
2023-01-20T18:14:47.484Z [LEDDEVICE_PHILIPSHUEV2] (LedDevicePhilipsHueV2.cpp:352) Stream status                 : inactive
2023-01-20T18:14:47.484Z [LEDDEVICE_PHILIPSHUEV2] (LedDevicePhilipsHueV2.cpp:847) Start entertainment stream
2023-01-20T18:14:47.484Z [LEDDEVICE] (ProviderRestApi.cpp:170) PUT begin: [https://192.168.1.3:443/clip/v2/resource/entertainment_configuration/14b3d2fa-d52f-4025-bf05-fc54000eda39] [{"action":"start"}]
2023-01-20T18:14:47.611Z [LEDDEVICE] (ProviderRestApi.cpp:191) PUT end (127 ms): [https://192.168.1.3:443/clip/v2/resource/entertainment_configuration/14b3d2fa-d52f-4025-bf05-fc54000eda39] [{"action":"start"}]
2023-01-20T18:14:47.611Z [LEDDEVICE] (ProviderRestApi.cpp:310) Reply.httpStatusCode [200]
2023-01-20T18:14:47.611Z [LEDDEVICE] (ProviderRestApi.cpp:170) GET begin: [https://192.168.1.3:443/clip/v2/resource/entertainment_configuration/14b3d2fa-d52f-4025-bf05-fc54000eda39] []
2023-01-20T18:14:47.645Z [LEDDEVICE] (ProviderRestApi.cpp:191) GET end (34 ms): [https://192.168.1.3:443/clip/v2/resource/entertainment_configuration/14b3d2fa-d52f-4025-bf05-fc54000eda39] []
2023-01-20T18:14:47.645Z [LEDDEVICE] (ProviderRestApi.cpp:310) Reply.httpStatusCode [200]
2023-01-20T18:14:47.647Z [LEDDEVICE_PHILIPSHUEV2] (LedDevicePhilipsHueV2.cpp:352) Group state                   : {"active_streamer":{"rid":"3a91a748-d600-4a22-b471-f884d0d1fb01","rtype":"auth_v1"},"channels":[{"channel_id":0,"members":[{"index":0,"service":{"rid":"d0563cd5-1225-48b9-abbf-92d053fc55d9","rtype":"entertainment"}},{"index":0,"service":{"rid":"92fd41bb-9c1c-487e-8d90-4510b9b24c48","rtype":"entertainment"}},{"index":2,"service":{"rid":"5501ca92-e622-4ec3-867b-27546a8e61cf","rtype":"entertainment"}},{"index":6,"service":{"rid":"d6fe9cdb-9c12-4f17-9ef2-401fbf548f2f","rtype":"entertainment"}}],"position":{"x":0.4,"y":0.8,"z":-0.4}},{"channel_id":1,"members":[{"index":1,"service":{"rid":"d0563cd5-1225-48b9-abbf-92d053fc55d9","rtype":"entertainment"}},{"index":1,"service":{"rid":"92fd41bb-9c1c-487e-8d90-4510b9b24c48","rtype":"entertainment"}},{"index":5,"service":{"rid":"d6fe9cdb-9c12-4f17-9ef2-401fbf548f2f","rtype":"entertainment"}}],"position":{"x":0.4,"y":0.8,"z":0}},{"channel_id":2,"members":[{"index":0,"service":{"rid":"385e5a28-cc18-4283-90d9-27f755e49d18","rtype":"entertainm
2023-01-20T18:14:47.647Z [LEDDEVICE_PHILIPSHUEV2] (LedDevicePhilipsHueV2.cpp:352) Stream status                 : active
2023-01-20T18:14:47.647Z [LEDDEVICE_PHILIPSHUEV2] (LedDevicePhilipsHueV2.cpp:852) The stream has started.
2023-01-20T18:14:48.257Z [LEDDEVICE_PHILIPSHUEV2] Philips Hue Entertaiment API successful connected! Start Streaming.
2023-01-20T18:14:51.293Z [LEDDEVICE_PHILIPSHUEV2] Release mbedtls
2023-01-20T18:14:51.293Z [LEDDEVICE] (ProviderRestApi.cpp:170) PUT begin: [https://192.168.1.3:443/clip/v2/resource/entertainment_configuration/14b3d2fa-d52f-4025-bf05-fc54000eda39] [{"action":"stop"}]
2023-01-20T18:14:51.397Z [LEDDEVICE] (ProviderRestApi.cpp:191) PUT end (104 ms): [https://192.168.1.3:443/clip/v2/resource/entertainment_configuration/14b3d2fa-d52f-4025-bf05-fc54000eda39] [{"action":"stop"}]
2023-01-20T18:14:51.397Z [LEDDEVICE] (ProviderRestApi.cpp:310) Reply.httpStatusCode [200]
2023-01-20T18:14:51.397Z [LEDDEVICE] (ProviderRestApi.cpp:170) GET begin: [https://192.168.1.3:443/clip/v2/resource/entertainment_configuration/14b3d2fa-d52f-4025-bf05-fc54000eda39] []
2023-01-20T18:14:51.419Z [LEDDEVICE] (ProviderRestApi.cpp:191) GET end (21 ms): [https://192.168.1.3:443/clip/v2/resource/entertainment_configuration/14b3d2fa-d52f-4025-bf05-fc54000eda39] []
2023-01-20T18:14:51.420Z [LEDDEVICE] (ProviderRestApi.cpp:310) Reply.httpStatusCode [200]
2023-01-20T18:14:51.422Z [LEDDEVICE_PHILIPSHUEV2] (LedDevicePhilipsHueV2.cpp:352) Group state                   : {"channels":[{"channel_id":0,"members":[{"index":0,"service":{"rid":"d0563cd5-1225-48b9-abbf-92d053fc55d9","rtype":"entertainment"}},{"index":0,"service":{"rid":"92fd41bb-9c1c-487e-8d90-4510b9b24c48","rtype":"entertainment"}},{"index":2,"service":{"rid":"5501ca92-e622-4ec3-867b-27546a8e61cf","rtype":"entertainment"}},{"index":6,"service":{"rid":"d6fe9cdb-9c12-4f17-9ef2-401fbf548f2f","rtype":"entertainment"}}],"position":{"x":0.4,"y":0.8,"z":-0.4}},{"channel_id":1,"members":[{"index":1,"service":{"rid":"d0563cd5-1225-48b9-abbf-92d053fc55d9","rtype":"entertainment"}},{"index":1,"service":{"rid":"92fd41bb-9c1c-487e-8d90-4510b9b24c48","rtype":"entertainment"}},{"index":5,"service":{"rid":"d6fe9cdb-9c12-4f17-9ef2-401fbf548f2f","rtype":"entertainment"}}],"position":{"x":0.4,"y":0.8,"z":0}},{"channel_id":2,"members":[{"index":0,"service":{"rid":"385e5a28-cc18-4283-90d9-27f755e49d18","rtype":"entertainment"}},{"index":0,"service":{"rid":"722b1dec-d270-41f3-8a74-ff56e3bc104d","rtype":"
2023-01-20T18:14:51.422Z [LEDDEVICE_PHILIPSHUEV2] (LedDevicePhilipsHueV2.cpp:352) Stream status                 : inactive
2023-01-20T18:14:51.422Z [LEDDEVICE_PHILIPSHUEV2] (LedDevicePhilipsHueV2.cpp:895) The stream has stopped
2023-01-20T18:14:55.309Z [WEBSOCKET] (JsonAPI.cpp:1250) log streaming activated for client ::ffff:192.168.1.19
```

Also attaching an image incase the above does not display properly

Screenshot 2023-01-23 at 11 49 15

The time taken for the identify to begin (when the command is received from the front end) and when the stream is stopped takes about 4 seconds (note that this also includes the 1 second cycling of RGB). There has to be something else at play here for the lag.

@dbell669 Could you confirm what device hyperhdr is running on?

**Comment by gibahjoe** [comment]
> I had philips hue working  and sending colors before the push that started to use the red blue green flashing. even with it disabled in the remote tab its still not handling the flash action well. it wont seem to send them until after I close the wizard. So I can set locations, but trying to ping them does not work.
> 
> 

Sorry. Which remote tab are you referring to?

**Comment by awawa-dev** [comment]
I was thinking about disabling the 'LED device', not USB grabber. On webos USB support is disabled and that button does nothing.
obraz

**Comment by dbell669** [comment]
yep that did it. turning off LED device made it update and identify in a much quicker manner.

**Comment by awawa-dev** [comment]
It gets trickier if user enabled the light device before running the wizard. Maybe it would be simpler to run just two json commands (they are already available) from JS wizard before displaying the dialog with Philips lamps at the end to 1) enable a color (black?) as an effect to have a video source for sure 2) turn the Philips Hue on (Led device component for the instance which is already configured and saved) which enables the streaming. And in Identify method do not initialize Philips Hue again but only check the status _isOn and if it's OK then write colors to the stream.

**Comment by awawa-dev** [comment]
To consider:  
```
// clear current effect, should be called also on exit  
requestPriorityClear();
// set color
setTimeout(function(){
	// rgb and duration: 0 = inf.
	requestSetColor(255, 255, 0, 0); 
}, 100);
// turn on led device if disabled
requestSetComponentState('LEDDEVICE',true);
```

**Comment by gibahjoe** [comment]
> It gets trickier if user enabled the light device before running the wizard. Maybe it would be simpler to run just two json commands (they are already available) from JS wizard before displaying the dialog with Philips lamps at the end to 1) enable a color (black?) as an effect to have a video source for sure 2) turn the Philips Hue on (Led device component for the instance which is already configured and saved) which enables the streaming. And in Identify method do not initialize Philips Hue again but only check the status _isOn and if it's OK then write colors to the stream.

There are some use cases this approach would not cover. 
1) user does not have an existing configuration saved (in which case current identify in this PR covers)
2) user has an existing configuration saved but is updating the configuration by changing the group ID or even the bridge (the identify would go to the old configuration)

Also, the identify in this PR is using a new instance of the Leddevice I believe so the _isOn variable would not be shared. Isnt that the case?
```
else if (subc == "identify")
		{
			ledDevice = LedDeviceFactory::construct(config);
			const QJsonObject& params = message["params"].toObject();
			ledDevice->identify(params);

			sendSuccessReply(full_command, tan);
		}
```

The Approach I was trying to take was to detect in the identify method if there is an active stream, pause it, perform the identification and then resume it. But the instances of the leddevice are different so still struggling with that.

**Comment by gibahjoe** [comment]
> To consider:
> 
> ```
> // clear current effect, should be called also on exit  
> requestPriorityClear();
> // set color
> setTimeout(function(){
> 	// rgb and duration: 0 = inf.
> 	requestSetColor(255, 255, 0, 0); 
> 	// turn on led device if disabled
>         requestSetComponentState('LEDDEVICE',true);
> }, 100);
> ```

This most definitely will work for identify(blink) in the led layout tab

**Comment by awawa-dev** [comment]
> Also, the identify in this PR is using a new instance of the Leddevice I believe so the _isOn variable would not be shared. Isnt that the case?

Yes, I will test if we could use final user instance. For initialization in Identify there are more potential problems like UDP stream handler and some Philips Hue routines has some autoresume mechanisms which may cause problems with overall HyperHDR state when something goes wrong during transmission in Identify (or if new Identify instance disrupts the user instance if it was running before: cascade of autoresumes), because it was not design for such operation either.

**Comment by awawa-dev** [comment]
I've modified the code to use the LED instance when API v2 is used (tested with small tweak only with v1). If you could test if it works in 2 scenarios: there is other LED device (eg. debug/file, press F5 in browser to make sure it's an actual server configuration) configured before running Philips Hue wizard  or there is already configured Philips Hue and it's running but we want to run the wizard again. `$('#btn_wiz_save').click();` in wizard probably should be better guarded to run it only once after the dialog with 'Identify' buttons is shown.

**Comment by gibahjoe** [comment]
Will take a look.

I have pushed up adding an identify to led layout tab.

Now, this is expected to work with other led devices please take a look. I had to update the signature of some other files. I am happy to change it if you have any issues

**Comment by awawa-dev** [comment]
As far as global signals go, I don't plan any changes there just for the single API method which doesn't need to be propagated further than the single instance: just add new method to the HyperHdrInstance  to set some new properties like index of the LED to blink and timeout (please use internal timers, you have direct communication from JsonAPI/API to HyperHdrInstance each running on different thread, preferably set new properties asynchronously instead of the blocking invoke) and later include them both in HyperHdrInstance ->updateResult processing which already includes similar solution for disabled LEDs.

**Comment by awawa-dev** [comment]
I think to use new identifyLed from HyperHdrInstance  for that purpose.

**Comment by gibahjoe** [comment]
This line ```	$('#btn_wiz_save').click();``` uses the wizard to close prematurely. Once I click on Identify, the wizard closes and reloads the page. Sometimes, the application recovers properly, sometimes it shows a blank page and I have to restart it. Either way, I am unable to identify from the wizard

I tested out the identify you just pushed and it works well on v2. 

If I comment out the line above, I am able to identify only if I have an existing Philips hue v2 configuration and I select the same entertainment configuration (group).

I also made some adjustments to workaround the lightscount errors.

I think a combination of this and the other one that initialized the UDP connection in identify should give us a working solution.

**Comment by awawa-dev** [comment]
> This line $('#btn_wiz_save').click(); causes the wizard to close prematurely. Once I click on Identify, the wizard closes and reloads the page. Sometimes, the application recovers properly, sometimes it shows a blank page and I have to restart it. Either way, I am unable to identify from the wizard

Thanks for the fix. This need to be investigates further in such case, cant reproduce it on my system...maybe some differences between our configurations and I tested it for API v1 (moved that part to v1 section in same function and changed caller id for the Identify) I will take a  look tomorrow. Which browser do you use and did you edit existing and working Philips Hue instance?

**Comment by awawa-dev** [comment]
OK, I think I have fixed it.

**Comment by dbell669** [comment]
Any other tests needed from my end before I start tinkering with the other types of led strips?

**Comment by awawa-dev** [comment]
@dbell669  it would be great if you could test again newest version. Beside changed 'identify' button in the wizard there is also a new 'identify' button in the context menu (https://github.com/awawa-dev/HyperHDR/pull/379). Try both if they work fine for your setup.

**Comment by gibahjoe** [comment]
I have confirmed they both work for my setup

**Comment by awawa-dev** [comment]
Yes, but @dbell669's configuration is/was more problematic and started these numerous changes in the wizard ;) It would be good to know the final result.

**Comment by dbell669** [comment]
Ok. Just tested. It seems like the lag issues on identification are gone, and the identify button in the led layout page works well.

**Comment by awawa-dev** [comment]
Thanks @dbell669 for the feedback. @gibahjoe I refactored the code reducing shared code between 2 Philips Hue classes (finally ~550 new lines instead of ~1700 in single class, it will be easier for me in future to maintain that driver) and fixed some minor issues e.g. saving/restoring state when V2 is used. You've done a really great job 👍 I have reviewed and refactored all the code and have no plans to make any further changes on my part. I'm wondering whether to include this PR in v19 and in the upcoming v20. I freeze v19beta2 ahead of final release, but we still have some time to test this PR. What do you think?

**Comment by gibahjoe** [comment]
Thank you. I think releasing earlier rather than later is better so we can get feedback from a wide range of users. So, v19.

**Comment by gotschi** [comment]
works really good for me, thanks!
is there a definitive go-to layout for the gradient? I'm seeing mismatches to the zone alignment and seem to not be able to make the top corner zones as wide as they really are.
maybe I'm doing something stupid here
https://imgur.com/a/6oRXYS1

**Comment by awawa-dev** [comment]
@gotschi did you try to use the context menu later in the LED layout designer to correct it later? You can resize them and change their position as you want. Usage: https://github.com/awawa-dev/HyperHDR/pull/379 In the wizard where you configure the hue options, the options are limited. I can add later few predefined lamps but I must now their size/location...beside the list is long and it's hard to find a proper element already.

**Comment by gotschi** [comment]
oh yes, changing the values in the properties menu works, I think it glitched out earlier for me
awesome! thanks

**Comment by awawa-dev** [comment]
@gibahjoe I post a short post on my blog for each version. May I use your photos in the description of the API v2 feature that you implemented in version 19?

**Comment by gibahjoe** [comment]
@awawa-dev Yes that's fine. Sorry just saw this.

**Pull request merged**
