### PR TITLE
Fix LUT calibration for grabber-less build configuration

### PR DESCRIPTION
**Pull request by satgit62**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by awawa-dev** [comment]
Something is wrong?

**Comment by satgit62** [comment]
Hello,

I was wondering if I should make this change to be able to calibrate the LUT under webOS?

https://github.com/awawa-dev/HyperHDR/pull/518#issuecomment-2025721396

`_lutCalibrator->incomingCommand(_instanceManager->getRootPath(), (_videoGrabber != nullptr) ? _videoGrabber->grabberWrapper() : nullptr, getActiveComponent(), checksum, _startColor, _endColor, limitedRange, saturation, luminance, gammaR, gammaG, gammaB, coef);`

**Comment by awawa-dev** [comment]
Yes, if the grabber is excluded from build process completely (for example: webOS) then this patch is necessary. You can re-open PR and I will merge it later.

**Comment by satgit62** [comment]
Hi, thanks for quick reply, I have reopened the PR for this change: `_lutCalibrator->incomingCommand(_instanceManager->getRootPath(), (_videoGrabber != nullptr) ? _videoGrabber->grabberWrapper() : nullptr, getActiveComponent(), checksum, _startColor, _endColor, limitedRange, saturation, luminance, gammaR, gammaG, gammaB, coef);`

**Pull request closed without merging**
