### PR TITLE
Update language file's

### PR DESCRIPTION
**Pull request by AstaRom**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

- Update language file's

### CODE REVIEW

**Comment by AstaRom** [comment]
Added translation files in accordance with the latest changes.
The previous request was closed as the changes were merged into the main branch.

**Comment by awawa-dev** [comment]
Hi @AstaRom 
Can I have a request for you to add two new translations to the non-English versions of resources? Soon they will appear on the master as I found that they are missing. Thank you in advance.
```
  "modal_old_password" : "Old password",
  "modal_new_password" : "New password"
```

**Comment by AstaRom** [comment]
Done. Also made some minor changes to unify between translation files.

**Comment by awawa-dev** [comment]
Thank you very much :)

**Comment by AstaRom** [comment]
Added the latest changes from the commit:

- [6190b2dace11cfcdd0749c4875e1c4e860b054b8](https://github.com/awawa-dev/HyperHDR/pull/605/commits/6190b2dace11cfcdd0749c4875e1c4e860b054b8)

**Pull request merged**
